const technologyTags = [
  "React",
  "Node",
  "Next.js",
  "TypeScript",
  "JavaScript",
  "Express",
  "Koa",
  "Vercel",
  "Firebase",
  "TanStack Query (React Query)",
  "Vite",
  "Tailwind CSS",
  "Stripe API",
  "Brevo (Sendinblue)",
  "ActiveCampaign",
  "Mailgun",
  "PHP",
  "CakePHP",
  "Symfony",
  "PostgreSQL",
  "MySQL",
  "Planetscale",
  "Objection.js",
  "Knex",
  "Auth0",
  "next-auth",
  "next-i18n",
  "Web3",
  "Solidity",
  "Polygon",
  "Cloudinary",
  "Filestack",
  "Uploadcare",
  "Webflow",
  "Notion API",
  "Google Sheets API",
  "Google Calendar API",
  "Jest",
  "Testing Library",
  "Cypress",
  "AWS",
  "AWS EC2",
  "AWS ALB",
  "AWS ECS",
  "AWS CloudFormation",
  "AWS Fargate",
  "AWS Lambda",
  "AWS S3",
  "AWS Route53",
  "AWS CloudFront",
  "AWS RDS",
  "AWS IAM",
  "AWS CloudWatch",
];

export default technologyTags;
